name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build and export the site
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          touch out/.nojekyll
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out
          git commit -m "Deploy static site"
          git remote set-url origin https://github.com/biclay/website.git
          git push -f origin `git subtree split --prefix out live`:live
